# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_path', models.CharField(max_length=500)),
                ('_md5', models.CharField(blank=True, db_column='md5', db_index=True, max_length=33)),
                ('modified_time', models.DateTimeField(verbose_name='Date Modified')),
                ('file_name', models.CharField(max_length=200)),
                ('album_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('3', 'face_recognition_done'), ('1', 'registered'), ('2', 'scanned'), ('0', 'unknown')], default='registered', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField(db_index=True)),
                ('image_creation_time', models.DateTimeField(blank=True, null=True)),
                ('image_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('image_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('img_format', models.CharField(max_length=5)),
            ],
        ),
    ]
