# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_path', models.CharField(max_length=500)),
                ('_md5', models.CharField(blank=True, db_column='md5', db_index=True, max_length=33)),
                ('modified_time', models.DateTimeField(verbose_name='Date Modified')),
                ('file_name', models.CharField(max_length=200)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotoManager.Album')),
            ],
        ),
    ]
