# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='file_name',
            field=models.CharField(default='Unknown file', max_length=20),
            preserve_default=False,
        ),
    ]
