# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='_md5',
            field=models.CharField(blank=True, db_column='md5', db_index=True, max_length=33),
        ),
    ]
