# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoManager', '0002_imagefile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='local_path',
            field=models.CharField(max_length=500),
        ),
    ]
