# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoManager', '0003_auto_20171108_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='md5',
            field=models.CharField(blank=True, max_length=33),
        ),
    ]
